name: Update Homepage

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 10 * * 6'  # Run weekly on Sunday at 10 AM UTC

jobs:
  update-homepage:
    runs-on: self-hosted
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest Docker images
        run: docker compose pull
        working-directory: /home/ansible/scripts/homepage-dev/app
